---
# JetStream Operator Helmリリースのデプロイ
- name: nats-ioリポジトリ追加
  community.kubernetes.helm_repository:
    name: nats
    repo_url: https://nats-io.github.io/k8s/helm/charts/
  tags: jetstream

- name: jetstream-operator Helmリリースのインストール
  community.kubernetes.helm:
    name: jetstream-operator
    chart_ref: nats/nats-operator
    release_namespace: jetstream
    create_namespace: true
    values: "{{ lookup('file', 'roles/k3s_core_helm/files/jetstream-values.yaml') | from_yaml }}"
    wait: true
  tags: jetstream
