---
# kube-prometheus-stack Helmリリースのデプロイ
- name: kube-prometheus-stack Helmリポジトリ追加
  community.kubernetes.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts
  tags: kube_prometheus_stack

- name: kube-prometheus-stack Helmリリースのインストール
  community.kubernetes.helm:
    name: kube-prometheus-stack
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: monitoring
    create_namespace: true
    values: "{{ lookup('file', 'roles/k3s_core_helm/files/kube-prometheus-stack-values.yaml') | from_yaml }}"
    wait: true
  tags: kube_prometheus_stack
