---
- name: Raspberry Piセットアップ（pi4専用）
  hosts: pi4
  become: yes
  roles:
    - network
    - ssh
    - update

- name: 全ノードでsshdを明示的に再起動する（pi4専用）
  hosts: pi4
  become: yes
  tasks:
    - name: sshdサービスを必ず再起動
      ansible.builtin.service:
        name: ssh
        state: restarted