- name: 公開鍵を配置する
  ansible.builtin.authorized_key:
    user: "{{ ssh_user }}"
    state: present
    key: "{{ lookup('file', ssh_pubkey_file) }}"

- name: 公開鍵認証を有効化する
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
    backup: yes
  notify: SSHサービスを再起動

- name: 公開鍵認証方式を有効化
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PubkeyAuthentication'
    line: 'PubkeyAuthentication yes'
    state: present
    backup: yes
  notify: SSHサービスを再起動

handlers:
  - name: SSHサービスを再起動
    ansible.builtin.service:
      name: ssh
      state: restarted
