---
# MetalLB関連セットアップ
- name: Create metallb-system namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: metallb-system
    state: present
    kubeconfig: files/k3s.yaml

- name: Add metallb Helm repo
  community.kubernetes.helm_repository:
    name: metallb
    repo_url: https://metallb.github.io/metallb
    kubeconfig: files/k3s.yaml

- name: Install/Upgrade MetalLB via Helm
  community.kubernetes.helm:
    name: metallb
    chart_ref: metallb/metallb
    release_namespace: metallb-system
    create_namespace: false
    state: present
    update_repo_cache: true
    kubeconfig: files/k3s.yaml
    values:
      speaker:
        tolerations:
          - key: node-type
            operator: Equal
            value: core
            effect: NoExecute
          - key: ingress
            operator: Equal
            value: "true"
            effect: NoSchedule

- name: Wait for MetalLB pods to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: metallb-system
    kubeconfig: files/k3s.yaml
  register: metallb_pods
  until: metallb_pods.resources | selectattr('status.phase', 'equalto', 'Running') | list | length == metallb_pods.resources | length
  retries: 20
  delay: 6

- name: Create MetalLB IPAddressPool
  kubernetes.core.k8s:
    state: present
    definition: |
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: lab-pool
        namespace: metallb-system
      spec:
        addresses:
          - 192.168.4.230-192.168.4.250
    kubeconfig: files/k3s.yaml

- name: Create MetalLB L2Advertisement
  kubernetes.core.k8s:
    state: present
    definition: |
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: lab-adv
        namespace: metallb-system
      spec:
        ipAddressPools:
          - lab-pool
    kubeconfig: files/k3s.yaml
