- name: ノードラベル付与（role=core, power=always-on, storage=zfs-nfs）
  delegate_to: localhost
  ansible.builtin.shell: |
    kubectl label node {{ k8s_node_name | default(inventory_hostname) }} role=core power=always-on storage=zfs-nfs --overwrite --kubeconfig files/k3s.yaml
  changed_when: false
  ignore_errors: true
  tags: k3s_core_node
