- name: ノードテイント付与（node-type=core:NoExecute）
  delegate_to: localhost
  ansible.builtin.shell: |
    kubectl taint node {{ k8s_node_name | default(inventory_hostname) }} node-type=core:NoExecute --overwrite --kubeconfig files/k3s.yaml
  changed_when: false
  ignore_errors: true
  tags: k3s_core_node
