---
# K3sワーカー/追加マスター用ロール
- name: クラスタjoin用tokenを取得（Ansibleコントローラから配布）
  ansible.builtin.copy:
    src: ../../files/node-token
    dest: /tmp/node-token
    owner: root
    group: root
    mode: '0600'
    remote_src: no

- name: K3sエージェントとしてjoin
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | K3S_URL="https://{{ groups['pi4-master'][0] }}:6443" K3S_TOKEN="$(cat /tmp/node-token)" sh -
  args:
    creates: /usr/local/bin/k3s-agent

- name: K3sサービスの状態確認
  ansible.builtin.service:
    name: k3s-agent
    state: started
    enabled: yes
