- name: ホスト名を変更する
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  register: hostname_result

- name: /etc/hosts をホスト名に合わせて修正
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127.0.1.1'
    line: "127.0.1.1   {{ hostname }}"
    state: present
    backup: yes
  register: hosts_result

- name: DNSサーバー・サーチドメインを /etc/dhcpcd.conf に追記
  ansible.builtin.blockinfile:
    path: /etc/dhcpcd.conf
    block: |
      static domain_name_servers={% for ns in dns_nameservers %}{{ ns }}{% if not loop.last %} {% endif %}{% endfor %}
      static domain_search={{ search_domain }}
    marker: "; ANSIBLE MANAGED BLOCK - DNS設定"
    insertafter: EOF
    backup: yes
  register: dhcpcd_result

- name: ホスト名やDNS設定が変更された場合のみ再起動
  ansible.builtin.reboot:
    msg: "ホスト名やネットワーク設定変更のため自動再起動します"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when:
    - hostname_result is changed
    - hosts_result is changed
    - dhcpcd_result is changed

- name: piユーザーをsudoersに追加しパスワード不要にする
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/010_pi_nopasswd
    create: yes
    mode: '0440'
    line: 'pi ALL=(ALL) NOPASSWD:ALL'
    state: present
