- name: ノードラベル付与（role=ingress, power=always-on）
  delegate_to: localhost
  ansible.builtin.shell: |
    kubectl label node {{ k8s_node_name | default(inventory_hostname) }} role=ingress power=always-on --overwrite --kubeconfig files/k3s.yaml
  changed_when: false
  ignore_errors: true
  tags: k3s_ingress_node
