- name: ノードテイント付与（ingress=true:NoSchedule）
  delegate_to: localhost
  ansible.builtin.shell: |
    kubectl taint node {{ k8s_node_name | default(inventory_hostname) }} ingress=true:NoSchedule --overwrite  --kubeconfig files/k3s.yaml
  changed_when: false
  ignore_errors: true
  tags: k3s_ingress_node
