---
# k3s agent（ワーカー）ノードのセットアップ
- name: Check if k3s-agent service is running
  shell: systemctl is-active k3s-agent || true
  register: k3s_agent_service_status
  changed_when: false

- name: Join worker node to cluster
  shell: |
    curl -sfL https://get.k3s.io | \
      INSTALL_K3S_VERSION="{{ k3s_version }}" \
      K3S_TOKEN="{{ cluster_token }}" \
      sh -s - agent \
      --server https://{{ vip }}:6443 \
      --node-ip {{ ansible_host }}
  when:
    - k3s_agent_service_status.stdout != 'active'
