---
- name: Base setup
  hosts: pi4
  become: yes
  tags: base
  roles:
    - network
    - ssh
    - update

- name: K3s master (HA)
  hosts: pi4-master
  become: yes
  roles:
    - k3s_common
    - k3s_server

- name: K3s worker
  hosts: pi4-worker
  become: yes
  roles:
    - k3s_common
    - k3s_agent

- name: Restart sshd
  hosts: pi4
  become: yes
  tags: base
  tasks:
    - name: Restart sshd service
      ansible.builtin.service:
        name: ssh
        state: restarted

- name: Configure kubectl
  hosts: localhost
  connection: local
  gather_facts: false
  tags:
    - configure-controller
  roles:
    # - controller-config