---
# k3s関連のクリーンアップ（アンインストール＆残骸削除）
- name: Stop k3s/k3s-agent service if running
  shell: |
    systemctl stop k3s || true
    systemctl stop k3s-agent || true
  ignore_errors: true

- name: Uninstall k3s (if installed)
  shell: |
    /usr/local/bin/k3s-uninstall.sh || true
    /usr/local/bin/k3s-agent-uninstall.sh || true
  ignore_errors: true

- name: Remove k3s data directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/rancher
    - /var/lib/rancher
    - /var/lib/kubelet
    - /var/lib/cni
    - /run/flannel
    - /etc/cni
    - /var/lib/containerd
    - /var/lib/calico
    - /opt/cni
    - /var/log/pods
    - /var/log/containers
  ignore_errors: true

- name: Remove k3s/kubectl binaries if present
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/local/bin/k3s
    - /usr/local/bin/k3s-agent
    - /usr/local/bin/kubectl
    - /usr/local/bin/crictl
    - /usr/local/bin/ctr
  ignore_errors: true
